"""First Migration

Revision ID: 89413af7435e
Revises: 8d547ec2903c
Create Date: 2024-05-02 16:48:01.514202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89413af7435e'
down_revision = '8d547ec2903c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_categories')
    # ### end Alembic commands ###
